# Generated by Django 2.2.28 on 2022-11-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
