# Generated by Django 2.2.28 on 2022-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0002_auto_20221117_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
